version: '3.1'

services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wapiti
      MYSQL_DATABASE: wapiti
    ports:
      - "3306:3306"
  postgresdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: wapiti
      POSTGRES_DB: wapiti
    ports:
      - "5432:5432"
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - mysqldb
      - postgresdb
